backend:
  name: github
  repo: "testcrmax/TheLoneMoon"
  branch: "master"

media_folder: "static/img/uploads"
public_folder: "/img/uploads"

collections:
  - name: "pages"
    label: "Pages"
    folder: "site/content"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
